# :schema node_modules/wrangler/config-schema.json
name = "ymo-dev"
compatibility_date = "2025-02-16"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/", binding = "ASSETS" }

# Enable Node.js compatibility
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "ymo.dev"
database_id = "7cf99191-e9af-4b02-a869-fa10b5177a4b"
